# Generated by Django 4.2 on 2023-11-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_article_categories_comment_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="headline",
            field=models.TextField(
                default=None, max_length=200, verbose_name="headline"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="date_time_edited",
            field=models.DateTimeField(auto_now=True, verbose_name="date_time_edited"),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_time_posted",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date_time_posted"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_time_edited",
            field=models.DateTimeField(auto_now=True, verbose_name="date_time_edited"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_time_posted",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date_time_posted"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date_joined"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=20, verbose_name="last_name"),
        ),
    ]
