# Generated by Django 4.2.6 on 2023-11-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_article_headline_alter_article_date_time_edited_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="contents",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="contents",
            new_name="content",
        ),
    ]
