# Generated by Django 4.2.6 on 2023-11-18 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_contents_article_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.article"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="posted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="CommentSection",
        ),
    ]
