# Generated by Django 4.2.6 on 2023-11-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_article_alter_comment_posted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_time_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
