# Generated by Django 4.2.6 on 2023-11-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_article_date_time_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
