# Generated by Django 4.2.6 on 2023-12-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_date_time_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.IntegerField(blank=True, null=True, verbose_name='profile_picture'),
        ),
    ]
