# Generated by Django 4.2.6 on 2023-12-14 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite_categories',
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_categories',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='favourites'),
            preserve_default=False,
        ),
    ]
